REM INSERTING into TBLFINE
SET DEFINE OFF;
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (1,1,3,to_date('08-APR-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (2,3,2,to_date('12-APR-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (3,5,4,to_date('17-APR-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (4,7,1,to_date('22-APR-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (5,9,5,to_date('27-APR-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (6,11,4,to_date('02-MAY-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (7,13,2,to_date('08-MAY-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (8,15,3,to_date('13-MAY-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (9,17,1,to_date('18-MAY-24','DD-MON-RR'));
Insert into TBLFINE (FINE_ID,USER_ID,FINE_AMOUNT,FINE_DATE) values (10,19,5,to_date('24-MAY-24','DD-MON-RR'));
