REM INSERTING into TBLLIBRARYDEPARTMENT
SET DEFINE OFF;
Insert into TBLLIBRARYDEPARTMENT (LIBRARY_DEPARTMENT_ID,NAME) values (1,'Business ');
Insert into TBLLIBRARYDEPARTMENT (LIBRARY_DEPARTMENT_ID,NAME) values (2,'Natural Sciences');
Insert into TBLLIBRARYDEPARTMENT (LIBRARY_DEPARTMENT_ID,NAME) values (3,'Social Sciences');
Insert into TBLLIBRARYDEPARTMENT (LIBRARY_DEPARTMENT_ID,NAME) values (4,'Engineering ');
Insert into TBLLIBRARYDEPARTMENT (LIBRARY_DEPARTMENT_ID,NAME) values (5,'Information Technology');
