REM INSERTING into TBLLIBRARYFEEDBACK
SET DEFINE OFF;
Insert into TBLLIBRARYFEEDBACK (FEEDBACK_ID,USER_ID,FEEDBACK_DATE,CLEANLINESS_SCORE,MAINTENANCE_SCORE,AVAILABILITY_HELPFULNESS_SCORE,ADEQUACY_BOOK_COLLECTION_SCORE) values (1,1,to_date('10-MAY-23','DD-MON-RR'),3,4,4,5);
Insert into TBLLIBRARYFEEDBACK (FEEDBACK_ID,USER_ID,FEEDBACK_DATE,CLEANLINESS_SCORE,MAINTENANCE_SCORE,AVAILABILITY_HELPFULNESS_SCORE,ADEQUACY_BOOK_COLLECTION_SCORE) values (2,2,to_date('12-AUG-23','DD-MON-RR'),4,5,5,5);
Insert into TBLLIBRARYFEEDBACK (FEEDBACK_ID,USER_ID,FEEDBACK_DATE,CLEANLINESS_SCORE,MAINTENANCE_SCORE,AVAILABILITY_HELPFULNESS_SCORE,ADEQUACY_BOOK_COLLECTION_SCORE) values (3,3,to_date('07-OCT-23','DD-MON-RR'),4,4,4,4);
Insert into TBLLIBRARYFEEDBACK (FEEDBACK_ID,USER_ID,FEEDBACK_DATE,CLEANLINESS_SCORE,MAINTENANCE_SCORE,AVAILABILITY_HELPFULNESS_SCORE,ADEQUACY_BOOK_COLLECTION_SCORE) values (4,4,to_date('03-NOV-23','DD-MON-RR'),4,2,2,2);
